import { MetroSighting, LINE4_STATIONS } from "./types";

const L4_COLOR = "#E3000B";

export const MOCK_SIGHTINGS: MetroSighting[] = [
  {
    id: "1",
    lineName: "Line 4",
    lineColor: L4_COLOR,
    stationName: "Tunis Marine",
    position: LINE4_STATIONS[0].position,
    reportedBy: "commuter_tn",
    reportedAt: new Date(Date.now() - 3 * 60000),
    confirmations: 14,
    note: "Departing now, on time",
  },
  {
    id: "2",
    lineName: "Line 4",
    lineColor: L4_COLOR,
    stationName: "Place de Barcelone",
    position: LINE4_STATIONS[2].position,
    reportedBy: "daily_rider",
    reportedAt: new Date(Date.now() - 8 * 60000),
    confirmations: 9,
    note: "Stopped at platform",
  },
  {
    id: "3",
    lineName: "Line 4",
    lineColor: L4_COLOR,
    stationName: "Bab Saadoun",
    position: LINE4_STATIONS[7].position,
    reportedBy: "metro_fan_216",
    reportedAt: new Date(Date.now() - 15 * 60000),
    confirmations: 6,
  },
  {
    id: "4",
    lineName: "Line 4",
    lineColor: L4_COLOR,
    stationName: "Bardo",
    position: LINE4_STATIONS[10].position,
    reportedBy: "tunis_transit",
    reportedAt: new Date(Date.now() - 22 * 60000),
    confirmations: 4,
    note: "Slight delay, 5 min",
  },
  {
    id: "5",
    lineName: "Line 4",
    lineColor: L4_COLOR,
    stationName: "Manouba",
    position: LINE4_STATIONS[15].position,
    reportedBy: "student_uni",
    reportedAt: new Date(Date.now() - 45 * 60000),
    confirmations: 2,
    note: "Heading toward Kheireddine",
  },
  {
    id: "6",
    lineName: "Line 4",
    lineColor: L4_COLOR,
    stationName: "Campus de Manouba",
    position: LINE4_STATIONS[21].position,
    reportedBy: "campus_daily",
    reportedAt: new Date(Date.now() - 2 * 60000),
    confirmations: 11,
    photoUrl: undefined,
  },
];
